---
name: Jsonlint-CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ixxel/unit-tests-alpine:latest
    steps:
    - name: Git clone repo
      uses: actions/checkout@v2
    - name: Jsonlint scan
      uses: ixxeL-actions/jsonlint@main
      with:
        extensions: '"json,JSON"'
        environment: '""'
        fix: 'true'
        working-dir: './test.json'